### ISSUE TITLE
Unit Tests!

### ISSUE THREAD

**Issue by sganesh1975** [tejasshahu/Teashop-app-using-ReactJS-DjangoRestFramework#1]
@tejasshahu Where are the unit tests? Have you used any unit testing framework before?

**Comment by tejasshahu** [comment]
> @tejasshahu Where are the unit tests? Have you used any unit testing framework before?

Hi @sganesh1975 
Here I have not created unit test cases. Because it was not mentioned in the task requirements. 
But Yes, I have developed unit test cases using "qunitjs" framework and python's "unittest" framework.
Django also provides to create its own test cases for testing created APIs.
